version: '3'

services:

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    # networks:
    #   - kafka-net
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.4.0
    # networks:
    #   - kafka-net
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./volumes/kafka/docker.sock:/var/run/docker.sock

